version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Depencancies 
          command: npm install
      - run:
          name: Run SonarQube Scan
          command: |
           export SONAR_TOKEN=$d16a87a5ad763c3fb30b01eba86879dea2a6e9da
            sonar-scanner \
              -Dsonar.projectKey=YourProjectKey \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=PraneVanmali \
              -Dsonar.login=$d16a87a5ad763c3fb30b01eba86879dea2a6e9da

           
            # Add sonar-scanner configuration here once the application code is added

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build

